hash-format = "sha256"

[[files]]
file = "mods/CottageCraftAxolotls-1.1.0-1.20.1+.jar"

[[files]]
file = "mods/accurate-block-placement-reborn.pw.toml"
metafile = true

[[files]]
file = "mods/ad-astra.pw.toml"
metafile = true

[[files]]
file = "mods/additional-lanterns.pw.toml"
metafile = true

[[files]]
file = "mods/advancement-plaques-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/adventurez.pw.toml"
metafile = true

[[files]]
file = "mods/alternate-current.pw.toml"
metafile = true

[[files]]
file = "mods/amarite-1.5-1.0.8.jar"

[[files]]
file = "mods/anvilfixreborn.pw.toml"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/aquamirae-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/audioplayer.pw.toml"
metafile = true

[[files]]
file = "mods/auth-me.pw.toml"
metafile = true

[[files]]
file = "mods/automobility.pw.toml"
metafile = true

[[files]]
file = "mods/axolotlbuckets-1.2.0+1.20.jar"

[[files]]
file = "mods/azurelib-armor.pw.toml"
metafile = true

[[files]]
file = "mods/badpackets.pw.toml"
metafile = true

[[files]]
file = "mods/balm-fabric-1.20.1-7.1.4.jar"

[[files]]
file = "mods/bclib.pw.toml"
metafile = true

[[files]]
file = "mods/beachparty.pw.toml"
metafile = true

[[files]]
file = "mods/beautify-refabricated.pw.toml"
metafile = true

[[files]]
file = "mods/beneath-the-wetlands.pw.toml"
metafile = true

[[files]]
file = "mods/better-clouds-1.3.10+1.20.1.jar"

[[files]]
file = "mods/better-ping-display-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/better-sodium-video-settings-button.pw.toml"
metafile = true

[[files]]
file = "mods/better-stats.pw.toml"
metafile = true

[[files]]
file = "mods/betterend.pw.toml"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
metafile = true

[[files]]
file = "mods/blahaj.pw.toml"
metafile = true

[[files]]
file = "mods/blast.pw.toml"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
metafile = true

[[files]]
file = "mods/bookshelf.pw.toml"
metafile = true

[[files]]
file = "mods/borderless-mining.pw.toml"
metafile = true

[[files]]
file = "mods/botarium.pw.toml"
metafile = true

[[files]]
file = "mods/bountiful-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/camera-utils.pw.toml"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
metafile = true

[[files]]
file = "mods/charm-of-undying.pw.toml"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
metafile = true

[[files]]
file = "mods/choicetheorems-overhauled-village.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
metafile = true

[[files]]
file = "mods/combat-roll.pw.toml"
metafile = true

[[files]]
file = "mods/comforts.pw.toml"
metafile = true

[[files]]
file = "mods/connected-glass.pw.toml"
metafile = true

[[files]]
file = "mods/connectible-chains.pw.toml"
metafile = true

[[files]]
file = "mods/connectivity.pw.toml"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
metafile = true

[[files]]
file = "mods/couplings.pw.toml"
metafile = true

[[files]]
file = "mods/creeper-overhaul.pw.toml"
metafile = true

[[files]]
file = "mods/creeper-spores.pw.toml"
metafile = true

[[files]]
file = "mods/cristel-lib.pw.toml"
metafile = true

[[files]]
file = "mods/croptopia.pw.toml"
metafile = true

[[files]]
file = "mods/cull-less-leaves.pw.toml"
metafile = true

[[files]]
file = "mods/cupboard.pw.toml"
metafile = true

[[files]]
file = "mods/dark-loading-screen.pw.toml"
metafile = true

[[files]]
file = "mods/dawn.pw.toml"
metafile = true

[[files]]
file = "mods/detail-armor-bar.pw.toml"
metafile = true

[[files]]
file = "mods/dimensionaltraders.pw.toml"
metafile = true

[[files]]
file = "mods/do-a-barrel-roll.pw.toml"
metafile = true

[[files]]
file = "mods/do-api.pw.toml"
metafile = true

[[files]]
file = "mods/dragonloot.pw.toml"
metafile = true

[[files]]
file = "mods/dungeon-and-taverns.pw.toml"
metafile = true

[[files]]
file = "mods/dungeon-difficulty.pw.toml"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
metafile = true

[[files]]
file = "mods/easiervillagertrading.pw.toml"
metafile = true

[[files]]
file = "mods/eating-animation-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/elytra-slot.pw.toml"
metafile = true

[[files]]
file = "mods/emerald-geodes.pw.toml"
metafile = true

[[files]]
file = "mods/enchancement.pw.toml"
metafile = true

[[files]]
file = "mods/enderman-overhaul.pw.toml"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
metafile = true

[[files]]
file = "mods/equipment-compare-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/explorify.pw.toml"
metafile = true

[[files]]
file = "mods/explosive-enhancement-1.2.1-1.20.x.jar"

[[files]]
file = "mods/extra-alchemy.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-disable-custom-worlds-advice.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-waystones.pw.toml"
metafile = true

[[files]]
file = "mods/falling-leaves-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/falling-tree.pw.toml"
metafile = true

[[files]]
file = "mods/farmers-delight-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/ferritecore-6.0.0-fabric.jar"

[[files]]
file = "mods/forge-config-api-port-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/framework-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/friends-and-foes.pw.toml"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
metafile = true

[[files]]
file = "mods/goblintraders-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
metafile = true

[[files]]
file = "mods/hardcorerevival-fabric-1.20-12.0.0.jar"

[[files]]
file = "mods/hearth-and-home.pw.toml"
metafile = true

[[files]]
file = "mods/held-item-info.pw.toml"
metafile = true

[[files]]
file = "mods/hole-filler-mod.pw.toml"
metafile = true

[[files]]
file = "mods/hopo-better-underwater-ruins.pw.toml"
metafile = true

[[files]]
file = "mods/icarus.pw.toml"
metafile = true

[[files]]
file = "mods/iceberg-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/immersive-aircraft.pw.toml"
metafile = true

[[files]]
file = "mods/immersive-paintings.pw.toml"
metafile = true

[[files]]
file = "mods/impersonate.pw.toml"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
metafile = true

[[files]]
file = "mods/inmis.pw.toml"
metafile = true

[[files]]
file = "mods/inmisaddon.pw.toml"
metafile = true

[[files]]
file = "mods/invisibleframes-1.1.0+1.20.jar"

[[files]]
file = "mods/irisshaders.pw.toml"
metafile = true

[[files]]
file = "mods/item-collectors.pw.toml"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
metafile = true

[[files]]
file = "mods/jewelry.pw.toml"
metafile = true

[[files]]
file = "mods/journeymap-1.20.1-5.9.15-fabric.jar"

[[files]]
file = "mods/journeymap-integration.pw.toml"
metafile = true

[[files]]
file = "mods/kambrik.pw.toml"
metafile = true

[[files]]
file = "mods/labels.pw.toml"
metafile = true

[[files]]
file = "mods/lets-do-bakery.pw.toml"
metafile = true

[[files]]
file = "mods/lets-do-candlelight.pw.toml"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/lootr-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/lovely-snails.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-furniture.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-lights-and-lamps.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-paths-and-pavings.pw.toml"
metafile = true

[[files]]
file = "mods/mavapi.pw.toml"
metafile = true

[[files]]
file = "mods/mavm.pw.toml"
metafile = true

[[files]]
file = "mods/mcdar.pw.toml"
metafile = true

[[files]]
file = "mods/measurements.pw.toml"
metafile = true

[[files]]
file = "mods/memoryleakfix-fabric-1.17+-1.1.2.jar"

[[files]]
file = "mods/midnightlib.pw.toml"
metafile = true

[[files]]
file = "mods/model-gap-fix.pw.toml"
metafile = true

[[files]]
file = "mods/modmenu-7.2.1.jar"

[[files]]
file = "mods/more-armor-trims.pw.toml"
metafile = true

[[files]]
file = "mods/more-axolotls.pw.toml"
metafile = true

[[files]]
file = "mods/more-mob-variants.pw.toml"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
metafile = true

[[files]]
file = "mods/moyai-1.20-2.0.2-fabric.jar"

[[files]]
file = "mods/mru.pw.toml"
metafile = true

[[files]]
file = "mods/naturalist.pw.toml"
metafile = true

[[files]]
file = "mods/nether-depths-upgrade.pw.toml"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
metafile = true

[[files]]
file = "mods/numismatic-overhaul.pw.toml"
metafile = true

[[files]]
file = "mods/nvidium-0.2.1-beta.jar"

[[files]]
file = "mods/obscure-api-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
metafile = true

[[files]]
file = "mods/pack-it-up.pw.toml"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
metafile = true

[[files]]
file = "mods/pehkui.pw.toml"
metafile = true

[[files]]
file = "mods/pick-up-notifier.pw.toml"
metafile = true

[[files]]
file = "mods/playeranimator.pw.toml"
metafile = true

[[files]]
file = "mods/plushie-mod.pw.toml"
metafile = true

[[files]]
file = "mods/project-543559.pw.toml"
metafile = true

[[files]]
file = "mods/projectile-damage-attribute.pw.toml"
metafile = true

[[files]]
file = "mods/promenade.pw.toml"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
metafile = true

[[files]]
file = "mods/qkl.pw.toml"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
metafile = true

[[files]]
file = "mods/replay-mod-fabric-and-forge.pw.toml"
metafile = true

[[files]]
file = "mods/replay-voice-chat.pw.toml"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
metafile = true

[[files]]
file = "mods/rhino.pw.toml"
metafile = true

[[files]]
file = "mods/rightclickharvest.pw.toml"
metafile = true

[[files]]
file = "mods/rune-crafting.pw.toml"
metafile = true

[[files]]
file = "mods/sculk-horn.pw.toml"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
metafile = true

[[files]]
file = "mods/selene.pw.toml"
metafile = true

[[files]]
file = "mods/shoulder-surfing-reloaded.pw.toml"
metafile = true

[[files]]
file = "mods/simple-copper-pipes.pw.toml"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
metafile = true

[[files]]
file = "mods/simplehats.pw.toml"
metafile = true

[[files]]
file = "mods/skin-layers-3d.pw.toml"
metafile = true

[[files]]
file = "mods/sky-villages-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/small-ships.pw.toml"
metafile = true

[[files]]
file = "mods/smarter-farmers-farmers-replant.pw.toml"
metafile = true

[[files]]
file = "mods/snowy-spirit.pw.toml"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
metafile = true

[[files]]
file = "mods/spell-engine.pw.toml"
metafile = true

[[files]]
file = "mods/spell-power.pw.toml"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
metafile = true

[[files]]
file = "mods/structory-towers.pw.toml"
metafile = true

[[files]]
file = "mods/structory.pw.toml"
metafile = true

[[files]]
file = "mods/structure-essentials-forge-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
metafile = true

[[files]]
file = "mods/supplementaries-squared.pw.toml"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
metafile = true

[[files]]
file = "mods/terrablender-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
metafile = true

[[files]]
file = "mods/the-graveyard-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/thermoo.pw.toml"
metafile = true

[[files]]
file = "mods/tidal-towns.pw.toml"
metafile = true

[[files]]
file = "mods/toms-storage-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/too-fast.pw.toml"
metafile = true

[[files]]
file = "mods/tooltipfix.pw.toml"
metafile = true

[[files]]
file = "mods/totemcounter-1.3.0+mc1.20.jar"

[[files]]
file = "mods/towns-and-towers.pw.toml"
metafile = true

[[files]]
file = "mods/trash-cans.pw.toml"
metafile = true

[[files]]
file = "mods/travelers-backpack-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
metafile = true

[[files]]
file = "mods/twigs.pw.toml"
metafile = true

[[files]]
file = "mods/ukulib-0.7.0+1.20.jar"

[[files]]
file = "mods/universal-graves.pw.toml"
metafile = true

[[files]]
file = "mods/vinery.pw.toml"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
metafile = true

[[files]]
file = "mods/voice-chat-interaction.pw.toml"
metafile = true

[[files]]
file = "mods/voidz.pw.toml"
metafile = true

[[files]]
file = "mods/wakes-0.2.0.jar"

[[files]]
file = "mods/welcome-to-meadow.pw.toml"
metafile = true

[[files]]
file = "mods/wizards.pw.toml"
metafile = true

[[files]]
file = "mods/woof.pw.toml"
metafile = true

[[files]]
file = "mods/xlpackets-1.0.4-1.20.x.jar"

[[files]]
file = "mods/yacl.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-api-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-desert-temples-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-end-island-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-jungle-temples-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-nether-fortresses-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-witch-huts-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-extras-fabric.pw.toml"
metafile = true

[[files]]
file = "options.txt"

[[files]]
file = "shaderpacks/ComplementaryUnbound_r5.0.1.zip"

[[files]]
file = "shaderpacks/ComplementaryUnbound_r5.0.1.zip.txt"
