name = "Ethereal SMP Official Modpack"
author = "TaikiHino"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9052e6b381e690df478c76cfee92ad4189859553e4acce5a1c8b9c6300c084e6"

[versions]
minecraft = "1.20.1"
quilt = "0.21.2"
