name = "Ethereal SMP Official Modpack"
author = "TaikiHino"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49fe757cc7b1266c8a3f137a36d40c9a98344bb81432cc2ecfb0b3396a4ceec1"

[versions]
minecraft = "1.20.1"
quilt = "0.22.0-beta.1"
