name = "Ethereal SMP Official Modpack"
author = "TaikiHino"
version = "1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ab68f35ddf143f8ca2130ffe74d744a0fb299dbba3c7f349e075e9548d9bedf"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
quilt = "0.21.0"
