name = "Ethereal SMP Official Modpack"
author = "TaikiHino"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "498de98365a4323680ca472687b4247c6f03590b5fc6a3be71fd94988662b3db"

[versions]
minecraft = "1.20.1"
quilt = "0.22.0-beta.1"
