name = "Ethereal SMP Official Modpack"
author = "TaikiHino"
version = "1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f37d87989fb522ce7a3c618eac4832aa0a6ef1cab63b800c75237db70b3e7536"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
quilt = "0.21.0"

[options]
no-internal-hashes = true
