name = "Ethereal SMP Official Modpack"
author = "TaikiHino"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c618cdad8b9c16ca15f3124d9e16abf49a1dcb89e595e09bc69c39c34851d93"

[versions]
minecraft = "1.20.1"
quilt = "0.22.0-beta.1"
